// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tx.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction represents a request or action submitted to the network
// THIS MUST MATCH lib.Transaction EXACTLY for signing
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"messageType"` // @gotags: json:"messageType"
	Msg           *anypb.Any             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Signature     *Signature             `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedHeight uint64                 `protobuf:"varint,4,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	Time          uint64                 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Fee           uint64                 `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	Memo          string                 `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	NetworkId     uint64                 `protobuf:"varint,8,opt,name=network_id,json=networkId,proto3" json:"networkID"` // @gotags: json:"networkID"
	ChainId       uint64                 `protobuf:"varint,9,opt,name=chain_id,json=chainId,proto3" json:"chainID"`       // @gotags: json:"chainID"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Transaction) GetMsg() *anypb.Any {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Transaction) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *Transaction) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Transaction) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *Transaction) GetNetworkId() uint64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *Transaction) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

// Signature is a BLS12-381 digital signature
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"publicKey"` // @gotags: json:"publicKey"
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *Signature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type MessageSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   []byte                 `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"fromAddress"` // @gotags: json:"fromAddress"
	ToAddress     []byte                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"toAddress"`       // @gotags: json:"toAddress"
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSend) Reset() {
	*x = MessageSend{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSend) ProtoMessage() {}

func (x *MessageSend) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSend.ProtoReflect.Descriptor instead.
func (*MessageSend) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MessageSend) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *MessageSend) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *MessageSend) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type FeeParams struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SendFee           uint64                 `protobuf:"varint,1,opt,name=send_fee,json=sendFee,proto3" json:"sendFee"`                                 // @gotags: json:"sendFee"
	CreatePlanFee     uint64                 `protobuf:"varint,2,opt,name=create_plan_fee,json=createPlanFee,proto3" json:"createPlanFee"`             // @gotags: json:"createPlanFee"
	SubscribeFee      uint64                 `protobuf:"varint,3,opt,name=subscribe_fee,json=subscribeFee,proto3" json:"subscribeFee"`                  // @gotags: json:"subscribeFee"
	ProcessBillingFee uint64                 `protobuf:"varint,4,opt,name=process_billing_fee,json=processBillingFee,proto3" json:"processBillingFee"` // @gotags: json:"processBillingFee"
	CancelFee         uint64                 `protobuf:"varint,5,opt,name=cancel_fee,json=cancelFee,proto3" json:"cancelFee"`                           // @gotags: json:"cancelFee"
	UpdatePlanFee     uint64                 `protobuf:"varint,6,opt,name=update_plan_fee,json=updatePlanFee,proto3" json:"updatePlanFee"`             // @gotags: json:"updatePlanFee"
	PauseFee          uint64                 `protobuf:"varint,7,opt,name=pause_fee,json=pauseFee,proto3" json:"pauseFee"`                              // @gotags: json:"pauseFee"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FeeParams) Reset() {
	*x = FeeParams{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeParams) ProtoMessage() {}

func (x *FeeParams) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeParams.ProtoReflect.Descriptor instead.
func (*FeeParams) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *FeeParams) GetSendFee() uint64 {
	if x != nil {
		return x.SendFee
	}
	return 0
}

func (x *FeeParams) GetCreatePlanFee() uint64 {
	if x != nil {
		return x.CreatePlanFee
	}
	return 0
}

func (x *FeeParams) GetSubscribeFee() uint64 {
	if x != nil {
		return x.SubscribeFee
	}
	return 0
}

func (x *FeeParams) GetProcessBillingFee() uint64 {
	if x != nil {
		return x.ProcessBillingFee
	}
	return 0
}

func (x *FeeParams) GetCancelFee() uint64 {
	if x != nil {
		return x.CancelFee
	}
	return 0
}

func (x *FeeParams) GetUpdatePlanFee() uint64 {
	if x != nil {
		return x.UpdatePlanFee
	}
	return 0
}

func (x *FeeParams) GetPauseFee() uint64 {
	if x != nil {
		return x.PauseFee
	}
	return 0
}

// Create a subscription plan / tier
type MessageCreatePlan struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CreatorAddress []byte                 `protobuf:"bytes,1,opt,name=creator_address,json=creatorAddress,proto3" json:"creatorAddress"`  // must be exactly 20 bytes — @gotags: json:"creatorAddress"
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                            // max 64 chars
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                              // max 280 chars
	Price          uint64                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`                                         // uSBX per billing cycle
	IntervalDays   uint64                 `protobuf:"varint,5,opt,name=interval_days,json=intervalDays,proto3" json:"intervalDays"`       // billing cadence in days (e.g. 30) — @gotags: json:"intervalDays"
	TrialDays      uint64                 `protobuf:"varint,6,opt,name=trial_days,json=trialDays,proto3" json:"trialDays"`                // 0 = no trial — @gotags: json:"trialDays"
	MaxSubscribers uint64                 `protobuf:"varint,7,opt,name=max_subscribers,json=maxSubscribers,proto3" json:"maxSubscribers"` // 0 = unlimited — @gotags: json:"maxSubscribers"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageCreatePlan) Reset() {
	*x = MessageCreatePlan{}
	mi := &file_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCreatePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCreatePlan) ProtoMessage() {}

func (x *MessageCreatePlan) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCreatePlan.ProtoReflect.Descriptor instead.
func (*MessageCreatePlan) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MessageCreatePlan) GetCreatorAddress() []byte {
	if x != nil {
		return x.CreatorAddress
	}
	return nil
}

func (x *MessageCreatePlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageCreatePlan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MessageCreatePlan) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MessageCreatePlan) GetIntervalDays() uint64 {
	if x != nil {
		return x.IntervalDays
	}
	return 0
}

func (x *MessageCreatePlan) GetTrialDays() uint64 {
	if x != nil {
		return x.TrialDays
	}
	return 0
}

func (x *MessageCreatePlan) GetMaxSubscribers() uint64 {
	if x != nil {
		return x.MaxSubscribers
	}
	return 0
}

// Subscribe to a plan
type MessageSubscribe struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubscriberAddress []byte                 `protobuf:"bytes,1,opt,name=subscriber_address,json=subscriberAddress,proto3" json:"subscriberAddress"` // 20 bytes — @gotags: json:"subscriberAddress"
	PlanId            uint64                 `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"planId"`                                 // @gotags: json:"planId"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MessageSubscribe) Reset() {
	*x = MessageSubscribe{}
	mi := &file_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSubscribe) ProtoMessage() {}

func (x *MessageSubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSubscribe.ProtoReflect.Descriptor instead.
func (*MessageSubscribe) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MessageSubscribe) GetSubscriberAddress() []byte {
	if x != nil {
		return x.SubscriberAddress
	}
	return nil
}

func (x *MessageSubscribe) GetPlanId() uint64 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

// Process a billing cycle for a subscription (called by validators / automation)
type MessageProcessBilling struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProcessorAddress []byte                 `protobuf:"bytes,1,opt,name=processor_address,json=processorAddress,proto3" json:"processorAddress"` // 20 bytes — earns billing reward — @gotags: json:"processorAddress"
	SubscriptionId   uint64                 `protobuf:"varint,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscriptionId"`      // @gotags: json:"subscriptionId"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageProcessBilling) Reset() {
	*x = MessageProcessBilling{}
	mi := &file_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageProcessBilling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageProcessBilling) ProtoMessage() {}

func (x *MessageProcessBilling) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageProcessBilling.ProtoReflect.Descriptor instead.
func (*MessageProcessBilling) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MessageProcessBilling) GetProcessorAddress() []byte {
	if x != nil {
		return x.ProcessorAddress
	}
	return nil
}

func (x *MessageProcessBilling) GetSubscriptionId() uint64 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

// Cancel a subscription
type MessageCancelSubscription struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubscriberAddress []byte                 `protobuf:"bytes,1,opt,name=subscriber_address,json=subscriberAddress,proto3" json:"subscriberAddress"` // 20 bytes — must match sub owner — @gotags: json:"subscriberAddress"
	SubscriptionId    uint64                 `protobuf:"varint,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscriptionId"`         // @gotags: json:"subscriptionId"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MessageCancelSubscription) Reset() {
	*x = MessageCancelSubscription{}
	mi := &file_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCancelSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCancelSubscription) ProtoMessage() {}

func (x *MessageCancelSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCancelSubscription.ProtoReflect.Descriptor instead.
func (*MessageCancelSubscription) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MessageCancelSubscription) GetSubscriberAddress() []byte {
	if x != nil {
		return x.SubscriberAddress
	}
	return nil
}

func (x *MessageCancelSubscription) GetSubscriptionId() uint64 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

// Pause a subscription — billing frozen, access retained until period ends
type MessagePauseSubscription struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubscriberAddress []byte                 `protobuf:"bytes,1,opt,name=subscriber_address,json=subscriberAddress,proto3" json:"subscriberAddress"` // @gotags: json:"subscriberAddress"
	SubscriptionId    uint64                 `protobuf:"varint,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscriptionId"`         // @gotags: json:"subscriptionId"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MessagePauseSubscription) Reset() {
	*x = MessagePauseSubscription{}
	mi := &file_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePauseSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePauseSubscription) ProtoMessage() {}

func (x *MessagePauseSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePauseSubscription.ProtoReflect.Descriptor instead.
func (*MessagePauseSubscription) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MessagePauseSubscription) GetSubscriberAddress() []byte {
	if x != nil {
		return x.SubscriberAddress
	}
	return nil
}

func (x *MessagePauseSubscription) GetSubscriptionId() uint64 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

// Resume a paused subscription
type MessageResumeSubscription struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubscriberAddress []byte                 `protobuf:"bytes,1,opt,name=subscriber_address,json=subscriberAddress,proto3" json:"subscriberAddress"` // @gotags: json:"subscriberAddress"
	SubscriptionId    uint64                 `protobuf:"varint,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscriptionId"`         // @gotags: json:"subscriptionId"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MessageResumeSubscription) Reset() {
	*x = MessageResumeSubscription{}
	mi := &file_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResumeSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResumeSubscription) ProtoMessage() {}

func (x *MessageResumeSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResumeSubscription.ProtoReflect.Descriptor instead.
func (*MessageResumeSubscription) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{9}
}

func (x *MessageResumeSubscription) GetSubscriberAddress() []byte {
	if x != nil {
		return x.SubscriberAddress
	}
	return nil
}

func (x *MessageResumeSubscription) GetSubscriptionId() uint64 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

// Update a plan (creator only)
type MessageUpdatePlan struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CreatorAddress []byte                 `protobuf:"bytes,1,opt,name=creator_address,json=creatorAddress,proto3" json:"creatorAddress"`  // 20 bytes — must match plan creator — @gotags: json:"creatorAddress"
	PlanId         uint64                 `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"planId"`                         // @gotags: json:"planId"
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                            // empty = no change
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                              // empty = no change
	NewPrice       uint64                 `protobuf:"varint,5,opt,name=new_price,json=newPrice,proto3" json:"newPrice"`                   // 0 = no change — @gotags: json:"newPrice"
	MaxSubscribers uint64                 `protobuf:"varint,6,opt,name=max_subscribers,json=maxSubscribers,proto3" json:"maxSubscribers"` // 0 = no change — @gotags: json:"maxSubscribers"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageUpdatePlan) Reset() {
	*x = MessageUpdatePlan{}
	mi := &file_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUpdatePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpdatePlan) ProtoMessage() {}

func (x *MessageUpdatePlan) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpdatePlan.ProtoReflect.Descriptor instead.
func (*MessageUpdatePlan) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MessageUpdatePlan) GetCreatorAddress() []byte {
	if x != nil {
		return x.CreatorAddress
	}
	return nil
}

func (x *MessageUpdatePlan) GetPlanId() uint64 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *MessageUpdatePlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageUpdatePlan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MessageUpdatePlan) GetNewPrice() uint64 {
	if x != nil {
		return x.NewPrice
	}
	return 0
}

func (x *MessageUpdatePlan) GetMaxSubscribers() uint64 {
	if x != nil {
		return x.MaxSubscribers
	}
	return 0
}

type Plan struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorAddress []byte                 `protobuf:"bytes,2,opt,name=creator_address,json=creatorAddress,proto3" json:"creatorAddress"` // @gotags: json:"creatorAddress"
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price          uint64                 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	IntervalDays   uint64                 `protobuf:"varint,6,opt,name=interval_days,json=intervalDays,proto3" json:"intervalDays"`       // @gotags: json:"intervalDays"
	TrialDays      uint64                 `protobuf:"varint,7,opt,name=trial_days,json=trialDays,proto3" json:"trialDays"`                // @gotags: json:"trialDays"
	MaxSubscribers uint64                 `protobuf:"varint,8,opt,name=max_subscribers,json=maxSubscribers,proto3" json:"maxSubscribers"` // @gotags: json:"maxSubscribers"
	ActiveSubs     uint64                 `protobuf:"varint,9,opt,name=active_subs,json=activeSubs,proto3" json:"activeSubs"`             // @gotags: json:"activeSubs"
	CreatedHeight  uint64                 `protobuf:"varint,10,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"`   // @gotags: json:"createdHeight"
	Active         bool                   `protobuf:"varint,11,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{11}
}

func (x *Plan) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Plan) GetCreatorAddress() []byte {
	if x != nil {
		return x.CreatorAddress
	}
	return nil
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Plan) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Plan) GetIntervalDays() uint64 {
	if x != nil {
		return x.IntervalDays
	}
	return 0
}

func (x *Plan) GetTrialDays() uint64 {
	if x != nil {
		return x.TrialDays
	}
	return 0
}

func (x *Plan) GetMaxSubscribers() uint64 {
	if x != nil {
		return x.MaxSubscribers
	}
	return 0
}

func (x *Plan) GetActiveSubs() uint64 {
	if x != nil {
		return x.ActiveSubs
	}
	return 0
}

func (x *Plan) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *Plan) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type Subscription struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlanId            uint64                 `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"planId"`                                    // @gotags: json:"planId"
	SubscriberAddress []byte                 `protobuf:"bytes,3,opt,name=subscriber_address,json=subscriberAddress,proto3" json:"subscriberAddress"`    // @gotags: json:"subscriberAddress"
	PlanCreator       []byte                 `protobuf:"bytes,4,opt,name=plan_creator,json=planCreator,proto3" json:"planCreator"`                      // @gotags: json:"planCreator"
	StartedHeight     uint64                 `protobuf:"varint,5,opt,name=started_height,json=startedHeight,proto3" json:"startedHeight"`               // @gotags: json:"startedHeight"
	NextBillingHeight uint64                 `protobuf:"varint,6,opt,name=next_billing_height,json=nextBillingHeight,proto3" json:"nextBillingHeight"` // @gotags: json:"nextBillingHeight"
	TrialEndsHeight   uint64                 `protobuf:"varint,7,opt,name=trial_ends_height,json=trialEndsHeight,proto3" json:"trialEndsHeight"`       // 0 if no trial — @gotags: json:"trialEndsHeight"
	Status            string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`                                                   // active | paused | cancelled | trial | failed
	BillingCycle      uint64                 `protobuf:"varint,9,opt,name=billing_cycle,json=billingCycle,proto3" json:"billingCycle"`                  // @gotags: json:"billingCycle"
	LastBilledHeight  uint64                 `protobuf:"varint,10,opt,name=last_billed_height,json=lastBilledHeight,proto3" json:"lastBilledHeight"`   // @gotags: json:"lastBilledHeight"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{12}
}

func (x *Subscription) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Subscription) GetPlanId() uint64 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *Subscription) GetSubscriberAddress() []byte {
	if x != nil {
		return x.SubscriberAddress
	}
	return nil
}

func (x *Subscription) GetPlanCreator() []byte {
	if x != nil {
		return x.PlanCreator
	}
	return nil
}

func (x *Subscription) GetStartedHeight() uint64 {
	if x != nil {
		return x.StartedHeight
	}
	return 0
}

func (x *Subscription) GetNextBillingHeight() uint64 {
	if x != nil {
		return x.NextBillingHeight
	}
	return 0
}

func (x *Subscription) GetTrialEndsHeight() uint64 {
	if x != nil {
		return x.TrialEndsHeight
	}
	return 0
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Subscription) GetBillingCycle() uint64 {
	if x != nil {
		return x.BillingCycle
	}
	return 0
}

func (x *Subscription) GetLastBilledHeight() uint64 {
	if x != nil {
		return x.LastBilledHeight
	}
	return 0
}

type PlanCounter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanCounter) Reset() {
	*x = PlanCounter{}
	mi := &file_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanCounter) ProtoMessage() {}

func (x *PlanCounter) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanCounter.ProtoReflect.Descriptor instead.
func (*PlanCounter) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{13}
}

func (x *PlanCounter) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SubCounter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCounter) Reset() {
	*x = SubCounter{}
	mi := &file_tx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCounter) ProtoMessage() {}

func (x *SubCounter) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCounter.ProtoReflect.Descriptor instead.
func (*SubCounter) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{14}
}

func (x *SubCounter) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MessageStakeTrust struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StakerAddress []byte                 `protobuf:"bytes,1,opt,name=staker_address,json=stakerAddress,proto3" json:"stakerAddress"` // @gotags: json:"stakerAddress"
	TargetAddress []byte                 `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"targetAddress"` // @gotags: json:"targetAddress"
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageStakeTrust) Reset() {
	*x = MessageStakeTrust{}
	mi := &file_tx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStakeTrust) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStakeTrust) ProtoMessage() {}

func (x *MessageStakeTrust) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStakeTrust.ProtoReflect.Descriptor instead.
func (*MessageStakeTrust) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{15}
}

func (x *MessageStakeTrust) GetStakerAddress() []byte {
	if x != nil {
		return x.StakerAddress
	}
	return nil
}

func (x *MessageStakeTrust) GetTargetAddress() []byte {
	if x != nil {
		return x.TargetAddress
	}
	return nil
}

func (x *MessageStakeTrust) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type MessageProposeSlash struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InitiatorAddress []byte                 `protobuf:"bytes,1,opt,name=initiator_address,json=initiatorAddress,proto3" json:"initiatorAddress"` // @gotags: json:"initiatorAddress"
	TargetAddress    []byte                 `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"targetAddress"`          // @gotags: json:"targetAddress"
	Reason           string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageProposeSlash) Reset() {
	*x = MessageProposeSlash{}
	mi := &file_tx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageProposeSlash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageProposeSlash) ProtoMessage() {}

func (x *MessageProposeSlash) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageProposeSlash.ProtoReflect.Descriptor instead.
func (*MessageProposeSlash) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{16}
}

func (x *MessageProposeSlash) GetInitiatorAddress() []byte {
	if x != nil {
		return x.InitiatorAddress
	}
	return nil
}

func (x *MessageProposeSlash) GetTargetAddress() []byte {
	if x != nil {
		return x.TargetAddress
	}
	return nil
}

func (x *MessageProposeSlash) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MessageVoteSlash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoterAddress  []byte                 `protobuf:"bytes,1,opt,name=voter_address,json=voterAddress,proto3" json:"voterAddress"` // @gotags: json:"voterAddress"
	ProposalId    []byte                 `protobuf:"bytes,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposalId"`       // @gotags: json:"proposalId"
	Approve       bool                   `protobuf:"varint,3,opt,name=approve,proto3" json:"approve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageVoteSlash) Reset() {
	*x = MessageVoteSlash{}
	mi := &file_tx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageVoteSlash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageVoteSlash) ProtoMessage() {}

func (x *MessageVoteSlash) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageVoteSlash.ProtoReflect.Descriptor instead.
func (*MessageVoteSlash) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{17}
}

func (x *MessageVoteSlash) GetVoterAddress() []byte {
	if x != nil {
		return x.VoterAddress
	}
	return nil
}

func (x *MessageVoteSlash) GetProposalId() []byte {
	if x != nil {
		return x.ProposalId
	}
	return nil
}

func (x *MessageVoteSlash) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

type MessageResolveSlash struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResolverAddress []byte                 `protobuf:"bytes,1,opt,name=resolver_address,json=resolverAddress,proto3" json:"resolverAddress"` // @gotags: json:"resolverAddress"
	ProposalId      []byte                 `protobuf:"bytes,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposalId"`                // @gotags: json:"proposalId"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageResolveSlash) Reset() {
	*x = MessageResolveSlash{}
	mi := &file_tx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResolveSlash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResolveSlash) ProtoMessage() {}

func (x *MessageResolveSlash) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResolveSlash.ProtoReflect.Descriptor instead.
func (*MessageResolveSlash) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{18}
}

func (x *MessageResolveSlash) GetResolverAddress() []byte {
	if x != nil {
		return x.ResolverAddress
	}
	return nil
}

func (x *MessageResolveSlash) GetProposalId() []byte {
	if x != nil {
		return x.ProposalId
	}
	return nil
}

type MessageWithdrawStake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StakerAddress []byte                 `protobuf:"bytes,1,opt,name=staker_address,json=stakerAddress,proto3" json:"stakerAddress"` // @gotags: json:"stakerAddress"
	TargetAddress []byte                 `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"targetAddress"` // @gotags: json:"targetAddress"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithdrawStake) Reset() {
	*x = MessageWithdrawStake{}
	mi := &file_tx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithdrawStake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithdrawStake) ProtoMessage() {}

func (x *MessageWithdrawStake) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithdrawStake.ProtoReflect.Descriptor instead.
func (*MessageWithdrawStake) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{19}
}

func (x *MessageWithdrawStake) GetStakerAddress() []byte {
	if x != nil {
		return x.StakerAddress
	}
	return nil
}

func (x *MessageWithdrawStake) GetTargetAddress() []byte {
	if x != nil {
		return x.TargetAddress
	}
	return nil
}

type TrustStake struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	StakerAddress           []byte                 `protobuf:"bytes,1,opt,name=staker_address,json=stakerAddress,proto3" json:"stakerAddress"` // @gotags: json:"stakerAddress"
	TargetAddress           []byte                 `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"targetAddress"` // @gotags: json:"targetAddress"
	Amount                  uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status                  uint64                 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedHeight           uint64                 `protobuf:"varint,5,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"`                                 // @gotags: json:"createdHeight"
	WithdrawRequestedHeight uint64                 `protobuf:"varint,6,opt,name=withdraw_requested_height,json=withdrawRequestedHeight,proto3" json:"withdrawRequestedHeight"` // @gotags: json:"withdrawRequestedHeight"
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TrustStake) Reset() {
	*x = TrustStake{}
	mi := &file_tx_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustStake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustStake) ProtoMessage() {}

func (x *TrustStake) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustStake.ProtoReflect.Descriptor instead.
func (*TrustStake) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{20}
}

func (x *TrustStake) GetStakerAddress() []byte {
	if x != nil {
		return x.StakerAddress
	}
	return nil
}

func (x *TrustStake) GetTargetAddress() []byte {
	if x != nil {
		return x.TargetAddress
	}
	return nil
}

func (x *TrustStake) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TrustStake) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TrustStake) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *TrustStake) GetWithdrawRequestedHeight() uint64 {
	if x != nil {
		return x.WithdrawRequestedHeight
	}
	return 0
}

type SlashProposal struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProposalId           []byte                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposalId"`                   // @gotags: json:"proposalId"
	TargetAddress        []byte                 `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"targetAddress"`          // @gotags: json:"targetAddress"
	InitiatorAddress     []byte                 `protobuf:"bytes,3,opt,name=initiator_address,json=initiatorAddress,proto3" json:"initiatorAddress"` // @gotags: json:"initiatorAddress"
	Reason               string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	VotesFor             uint64                 `protobuf:"varint,5,opt,name=votes_for,json=votesFor,proto3" json:"votesFor"`             // @gotags: json:"votesFor"
	VotesAgainst         uint64                 `protobuf:"varint,6,opt,name=votes_against,json=votesAgainst,proto3" json:"votesAgainst"` // @gotags: json:"votesAgainst"
	Voters               [][]byte               `protobuf:"bytes,7,rep,name=voters,proto3" json:"voters,omitempty"`
	Status               uint64                 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	VotingDeadlineHeight uint64                 `protobuf:"varint,9,opt,name=voting_deadline_height,json=votingDeadlineHeight,proto3" json:"votingDeadlineHeight"` // @gotags: json:"votingDeadlineHeight"
	CreatedHeight        uint64                 `protobuf:"varint,10,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"`                       // @gotags: json:"createdHeight"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SlashProposal) Reset() {
	*x = SlashProposal{}
	mi := &file_tx_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlashProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlashProposal) ProtoMessage() {}

func (x *SlashProposal) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlashProposal.ProtoReflect.Descriptor instead.
func (*SlashProposal) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{21}
}

func (x *SlashProposal) GetProposalId() []byte {
	if x != nil {
		return x.ProposalId
	}
	return nil
}

func (x *SlashProposal) GetTargetAddress() []byte {
	if x != nil {
		return x.TargetAddress
	}
	return nil
}

func (x *SlashProposal) GetInitiatorAddress() []byte {
	if x != nil {
		return x.InitiatorAddress
	}
	return nil
}

func (x *SlashProposal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SlashProposal) GetVotesFor() uint64 {
	if x != nil {
		return x.VotesFor
	}
	return 0
}

func (x *SlashProposal) GetVotesAgainst() uint64 {
	if x != nil {
		return x.VotesAgainst
	}
	return 0
}

func (x *SlashProposal) GetVoters() [][]byte {
	if x != nil {
		return x.Voters
	}
	return nil
}

func (x *SlashProposal) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SlashProposal) GetVotingDeadlineHeight() uint64 {
	if x != nil {
		return x.VotingDeadlineHeight
	}
	return 0
}

func (x *SlashProposal) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

type StakerIndex struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetAddresses [][]byte               `protobuf:"bytes,1,rep,name=target_addresses,json=targetAddresses,proto3" json:"targetAddresses"` // @gotags: json:"targetAddresses"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StakerIndex) Reset() {
	*x = StakerIndex{}
	mi := &file_tx_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakerIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakerIndex) ProtoMessage() {}

func (x *StakerIndex) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakerIndex.ProtoReflect.Descriptor instead.
func (*StakerIndex) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{22}
}

func (x *StakerIndex) GetTargetAddresses() [][]byte {
	if x != nil {
		return x.TargetAddresses
	}
	return nil
}

type SlashProposalCreatedEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProposalId       []byte                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposalId"`                   // @gotags: json:"proposalId"
	TargetAddress    []byte                 `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"targetAddress"`          // @gotags: json:"targetAddress"
	InitiatorAddress []byte                 `protobuf:"bytes,3,opt,name=initiator_address,json=initiatorAddress,proto3" json:"initiatorAddress"` // @gotags: json:"initiatorAddress"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SlashProposalCreatedEvent) Reset() {
	*x = SlashProposalCreatedEvent{}
	mi := &file_tx_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlashProposalCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlashProposalCreatedEvent) ProtoMessage() {}

func (x *SlashProposalCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlashProposalCreatedEvent.ProtoReflect.Descriptor instead.
func (*SlashProposalCreatedEvent) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{23}
}

func (x *SlashProposalCreatedEvent) GetProposalId() []byte {
	if x != nil {
		return x.ProposalId
	}
	return nil
}

func (x *SlashProposalCreatedEvent) GetTargetAddress() []byte {
	if x != nil {
		return x.TargetAddress
	}
	return nil
}

func (x *SlashProposalCreatedEvent) GetInitiatorAddress() []byte {
	if x != nil {
		return x.InitiatorAddress
	}
	return nil
}

var File_tx_proto protoreflect.FileDescriptor

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\x12\x05types\x1a\x19google/protobuf/any.proto\"\xa3\x02\n" +
	"\vTransaction\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12&\n" +
	"\x03msg\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03msg\x12.\n" +
	"\tsignature\x18\x03 \x01(\v2\x10.types.SignatureR\tsignature\x12%\n" +
	"\x0ecreated_height\x18\x04 \x01(\x04R\rcreatedHeight\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x04R\x04time\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x04R\x03fee\x12\x12\n" +
	"\x04memo\x18\a \x01(\tR\x04memo\x12\x1d\n" +
	"\n" +
	"network_id\x18\b \x01(\x04R\tnetworkId\x12\x19\n" +
	"\bchain_id\x18\t \x01(\x04R\achainId\"H\n" +
	"\tSignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"g\n" +
	"\vMessageSend\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\fR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\fR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"\x87\x02\n" +
	"\tFeeParams\x12\x19\n" +
	"\bsend_fee\x18\x01 \x01(\x04R\asendFee\x12&\n" +
	"\x0fcreate_plan_fee\x18\x02 \x01(\x04R\rcreatePlanFee\x12#\n" +
	"\rsubscribe_fee\x18\x03 \x01(\x04R\fsubscribeFee\x12.\n" +
	"\x13process_billing_fee\x18\x04 \x01(\x04R\x11processBillingFee\x12\x1d\n" +
	"\n" +
	"cancel_fee\x18\x05 \x01(\x04R\tcancelFee\x12&\n" +
	"\x0fupdate_plan_fee\x18\x06 \x01(\x04R\rupdatePlanFee\x12\x1b\n" +
	"\tpause_fee\x18\a \x01(\x04R\bpauseFee\"\xf5\x01\n" +
	"\x11MessageCreatePlan\x12'\n" +
	"\x0fcreator_address\x18\x01 \x01(\fR\x0ecreatorAddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x04R\x05price\x12#\n" +
	"\rinterval_days\x18\x05 \x01(\x04R\fintervalDays\x12\x1d\n" +
	"\n" +
	"trial_days\x18\x06 \x01(\x04R\ttrialDays\x12'\n" +
	"\x0fmax_subscribers\x18\a \x01(\x04R\x0emaxSubscribers\"Z\n" +
	"\x10MessageSubscribe\x12-\n" +
	"\x12subscriber_address\x18\x01 \x01(\fR\x11subscriberAddress\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\x04R\x06planId\"m\n" +
	"\x15MessageProcessBilling\x12+\n" +
	"\x11processor_address\x18\x01 \x01(\fR\x10processorAddress\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\x04R\x0esubscriptionId\"s\n" +
	"\x19MessageCancelSubscription\x12-\n" +
	"\x12subscriber_address\x18\x01 \x01(\fR\x11subscriberAddress\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\x04R\x0esubscriptionId\"r\n" +
	"\x18MessagePauseSubscription\x12-\n" +
	"\x12subscriber_address\x18\x01 \x01(\fR\x11subscriberAddress\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\x04R\x0esubscriptionId\"s\n" +
	"\x19MessageResumeSubscription\x12-\n" +
	"\x12subscriber_address\x18\x01 \x01(\fR\x11subscriberAddress\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\x04R\x0esubscriptionId\"\xd1\x01\n" +
	"\x11MessageUpdatePlan\x12'\n" +
	"\x0fcreator_address\x18\x01 \x01(\fR\x0ecreatorAddress\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\x04R\x06planId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tnew_price\x18\x05 \x01(\x04R\bnewPrice\x12'\n" +
	"\x0fmax_subscribers\x18\x06 \x01(\x04R\x0emaxSubscribers\"\xd8\x02\n" +
	"\x04Plan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12'\n" +
	"\x0fcreator_address\x18\x02 \x01(\fR\x0ecreatorAddress\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x04R\x05price\x12#\n" +
	"\rinterval_days\x18\x06 \x01(\x04R\fintervalDays\x12\x1d\n" +
	"\n" +
	"trial_days\x18\a \x01(\x04R\ttrialDays\x12'\n" +
	"\x0fmax_subscribers\x18\b \x01(\x04R\x0emaxSubscribers\x12\x1f\n" +
	"\vactive_subs\x18\t \x01(\x04R\n" +
	"activeSubs\x12%\n" +
	"\x0ecreated_height\x18\n" +
	" \x01(\x04R\rcreatedHeight\x12\x16\n" +
	"\x06active\x18\v \x01(\bR\x06active\"\xf7\x02\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\x04R\x06planId\x12-\n" +
	"\x12subscriber_address\x18\x03 \x01(\fR\x11subscriberAddress\x12!\n" +
	"\fplan_creator\x18\x04 \x01(\fR\vplanCreator\x12%\n" +
	"\x0estarted_height\x18\x05 \x01(\x04R\rstartedHeight\x12.\n" +
	"\x13next_billing_height\x18\x06 \x01(\x04R\x11nextBillingHeight\x12*\n" +
	"\x11trial_ends_height\x18\a \x01(\x04R\x0ftrialEndsHeight\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12#\n" +
	"\rbilling_cycle\x18\t \x01(\x04R\fbillingCycle\x12,\n" +
	"\x12last_billed_height\x18\n" +
	" \x01(\x04R\x10lastBilledHeight\"#\n" +
	"\vPlanCounter\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"\"\n" +
	"\n" +
	"SubCounter\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"y\n" +
	"\x11MessageStakeTrust\x12%\n" +
	"\x0estaker_address\x18\x01 \x01(\fR\rstakerAddress\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\fR\rtargetAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"\x81\x01\n" +
	"\x13MessageProposeSlash\x12+\n" +
	"\x11initiator_address\x18\x01 \x01(\fR\x10initiatorAddress\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\fR\rtargetAddress\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"r\n" +
	"\x10MessageVoteSlash\x12#\n" +
	"\rvoter_address\x18\x01 \x01(\fR\fvoterAddress\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\fR\n" +
	"proposalId\x12\x18\n" +
	"\aapprove\x18\x03 \x01(\bR\aapprove\"a\n" +
	"\x13MessageResolveSlash\x12)\n" +
	"\x10resolver_address\x18\x01 \x01(\fR\x0fresolverAddress\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\fR\n" +
	"proposalId\"d\n" +
	"\x14MessageWithdrawStake\x12%\n" +
	"\x0estaker_address\x18\x01 \x01(\fR\rstakerAddress\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\fR\rtargetAddress\"\xed\x01\n" +
	"\n" +
	"TrustStake\x12%\n" +
	"\x0estaker_address\x18\x01 \x01(\fR\rstakerAddress\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\fR\rtargetAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x04R\x06status\x12%\n" +
	"\x0ecreated_height\x18\x05 \x01(\x04R\rcreatedHeight\x12:\n" +
	"\x19withdraw_requested_height\x18\x06 \x01(\x04R\x17withdrawRequestedHeight\"\xeb\x02\n" +
	"\rSlashProposal\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\fR\n" +
	"proposalId\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\fR\rtargetAddress\x12+\n" +
	"\x11initiator_address\x18\x03 \x01(\fR\x10initiatorAddress\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1b\n" +
	"\tvotes_for\x18\x05 \x01(\x04R\bvotesFor\x12#\n" +
	"\rvotes_against\x18\x06 \x01(\x04R\fvotesAgainst\x12\x16\n" +
	"\x06voters\x18\a \x03(\fR\x06voters\x12\x16\n" +
	"\x06status\x18\b \x01(\x04R\x06status\x124\n" +
	"\x16voting_deadline_height\x18\t \x01(\x04R\x14votingDeadlineHeight\x12%\n" +
	"\x0ecreated_height\x18\n" +
	" \x01(\x04R\rcreatedHeight\"8\n" +
	"\vStakerIndex\x12)\n" +
	"\x10target_addresses\x18\x01 \x03(\fR\x0ftargetAddresses\"\x90\x01\n" +
	"\x19SlashProposalCreatedEvent\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\fR\n" +
	"proposalId\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\fR\rtargetAddress\x12+\n" +
	"\x11initiator_address\x18\x03 \x01(\fR\x10initiatorAddressB.Z,github.com/canopy-network/go-plugin/contractb\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_tx_proto_goTypes = []any{
	(*Transaction)(nil),               // 0: types.Transaction
	(*Signature)(nil),                 // 1: types.Signature
	(*MessageSend)(nil),               // 2: types.MessageSend
	(*FeeParams)(nil),                 // 3: types.FeeParams
	(*MessageCreatePlan)(nil),         // 4: types.MessageCreatePlan
	(*MessageSubscribe)(nil),          // 5: types.MessageSubscribe
	(*MessageProcessBilling)(nil),     // 6: types.MessageProcessBilling
	(*MessageCancelSubscription)(nil), // 7: types.MessageCancelSubscription
	(*MessagePauseSubscription)(nil),  // 8: types.MessagePauseSubscription
	(*MessageResumeSubscription)(nil), // 9: types.MessageResumeSubscription
	(*MessageUpdatePlan)(nil),         // 10: types.MessageUpdatePlan
	(*Plan)(nil),                      // 11: types.Plan
	(*Subscription)(nil),              // 12: types.Subscription
	(*PlanCounter)(nil),               // 13: types.PlanCounter
	(*SubCounter)(nil),                // 14: types.SubCounter
	(*MessageStakeTrust)(nil),         // 15: types.MessageStakeTrust
	(*MessageProposeSlash)(nil),       // 16: types.MessageProposeSlash
	(*MessageVoteSlash)(nil),          // 17: types.MessageVoteSlash
	(*MessageResolveSlash)(nil),       // 18: types.MessageResolveSlash
	(*MessageWithdrawStake)(nil),      // 19: types.MessageWithdrawStake
	(*TrustStake)(nil),                // 20: types.TrustStake
	(*SlashProposal)(nil),             // 21: types.SlashProposal
	(*StakerIndex)(nil),               // 22: types.StakerIndex
	(*SlashProposalCreatedEvent)(nil), // 23: types.SlashProposalCreatedEvent
	(*anypb.Any)(nil),                 // 24: google.protobuf.Any
}
var file_tx_proto_depIdxs = []int32{
	24, // 0: types.Transaction.msg:type_name -> google.protobuf.Any
	1,  // 1: types.Transaction.signature:type_name -> types.Signature
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
